export const ASANA_LIBRARY = {
  "Asanas": [
    // ── BEGINNER ──
    { name: "Mountain Pose",              sanskrit: "Tadasana",                      level: "beginner",     description: "Foundation standing pose for alignment and grounding",                  cues: "Stand tall, feet together. Inhale — grow tall through crown. Exhale — root down through feet.",                                                          contraindications: [] },
    { name: "Cat Cow Pose",               sanskrit: "Marjariasana / Bitilasana",     level: "beginner",     description: "Spinal mobility and breath coordination",                                cues: "Hands and knees. Inhale — drop belly, lift chest (Cow). Exhale — round spine to ceiling, tuck chin (Cat).",                                  contraindications: [] },
    { name: "Child Pose",                 sanskrit: "Balasana",                      level: "beginner",     description: "Resting pose that calms the nervous system",                            cues: "Kneel, sit back on heels, fold forward, arms extended. Inhale — back expands. Exhale — sink deeper.",                                                contraindications: [] },
    { name: "Cobra Pose",                 sanskrit: "Bhujangasana",                  level: "beginner",     description: "Gentle backbend that strengthens the spine",                             cues: "Lie prone, hands under shoulders. Inhale — lift chest, elbows slightly bent. Exhale — lower down slowly.",                                                    contraindications: ["Slipped Disk"] },
    { name: "Bridge Pose",                sanskrit: "Setu Bandhasana",               level: "beginner",     description: "Strengthens the back and opens the chest",                              cues: "Lie on back, knees bent, feet flat. Inhale — press feet down, lift hips up. Exhale — hold or lower slowly.",                                                                     contraindications: ["Knee Injury"] },
    { name: "Wind Relieving Pose",        sanskrit: "Pawanamuktasana",               level: "beginner",     description: "Single knee to chest, releases gas and massages abdomen",               cues: "Lie on back. Inhale — bring right knee to chest. Exhale — press knee into abdomen. Hold 5 breaths. Release. Repeat with left knee.",                                                          contraindications: [] },
    { name: "Double Wind Relieving",      sanskrit: "Dwipad Pawanamuktasana",        level: "beginner",     description: "Both knees to chest, releases lower back and gas",                      cues: "Lie on back. Inhale — bring both knees to chest. Exhale — hug knees, press lower back into floor. Rock gently side to side.",                                                   contraindications: [] },
    { name: "Single Leg Raise",           sanskrit: "Ekapadottanasana",              level: "beginner",     description: "Supine single leg raise, strengthens core and hip flexors",             cues: "Lie on back, legs straight. Inhale — raise right leg to 90 degrees. Exhale — lower without touching floor. Repeat with left leg.",                                            contraindications: [] },
    { name: "Supine Spinal Twist",        sanskrit: "Jathara Parivartanasana",       level: "beginner",     description: "Lying twist that releases lower back and massages organs",              cues: "Lie on back, knees bent. Exhale — drop both knees to right. Inhale — back to centre. Exhale — drop to left. Repeat both sides.",                                                contraindications: [] },
    { name: "Prone Boat Pose",            sanskrit: "Naukasana",                     level: "beginner",     description: "Prone backbend lifting arms and legs, strengthens entire back",         cues: "Lie face down, arms forward. Inhale — lift arms, chest and legs off floor simultaneously. Exhale — lower down.",                                                          contraindications: [] },
    { name: "Balancing Table Pose",       sanskrit: "Dandayamana Bharmanasana",      level: "beginner",     description: "Opposite arm and leg lift from tabletop, improves balance",            cues: "Hands and knees. Inhale — extend right arm and left leg. Exhale — return. Repeat with left arm and right leg.",                                                             contraindications: [] },
    { name: "Butterfly Pose",             sanskrit: "Baddha Konasana",               level: "beginner",     description: "Hip opener in seated position",                                         cues: "Sit tall, soles together, knees drop to sides. Inhale — lengthen spine. Exhale — gently press knees toward floor.",                                               contraindications: ["Knee Cartilage Damage"] },
    { name: "Staff Pose",                 sanskrit: "Dandasana",                     level: "beginner",     description: "Foundation seated pose for alignment and core activation",              cues: "Sit, legs extended, hands beside hips. Inhale — grow tall. Exhale — flex feet, press thighs down.",                                                            contraindications: ["Slipped Disk"] },
    { name: "Thunderbolt Pose",           sanskrit: "Vajrasana",                     level: "beginner",     description: "Kneeling pose that aids digestion and focus",                           cues: "Kneel, sit back on heels, hands on thighs. Inhale — lengthen spine. Exhale — relax shoulders. Best after meals.",                                                                 contraindications: ["Knee Cartilage Damage", "Knee Injury"] },
    { name: "Legs Up The Wall",           sanskrit: "Viparita Karani",               level: "beginner",     description: "Restorative inversion for circulation and recovery",                   cues: "Lie on back, swing legs up against wall. Inhale — relax completely. Exhale — let gravity drain the legs.",                                                                      contraindications: ["High Blood Pressure"] },
    { name: "Reclining Bound Angle",      sanskrit: "Supta Baddha Konasana",         level: "beginner",     description: "Restorative hip opener in reclined position",                          cues: "Lie on back, soles together, knees drop to sides. Inhale — feel belly rise. Exhale — let hips soften.",                                    contraindications: [] },
    { name: "Tiger Pose",                 sanskrit: "Utthita Pada Bharmanasana",     level: "beginner",     description: "Tabletop leg lift for balance and back strength",                      cues: "Hands and knees. Inhale — lift right leg back and up, knee bent. Exhale — lower down. Repeat with left leg.",                                                               contraindications: ["Knee Cartilage Damage"] },
    { name: "Half Plank",                 sanskrit: "Ardha Phalakasana",             level: "beginner",     description: "Modified plank on forearms for core strength",                         cues: "Forearms on floor, elbows under shoulders. Inhale — hold body straight. Exhale — engage core, do not let hips sag.",                                              contraindications: [] },
    { name: "Side Reclining Leg Lift",    sanskrit: "Anantasana",                    level: "beginner",     description: "Side lying leg raise, strengthens core and inner thighs",              cues: "Lie on right side, prop head on hand. Inhale — lift top leg up. Exhale — lower without touching. Repeat on left side.",                                                                   contraindications: [] },
    { name: "Locust Pose",                sanskrit: "Salabhasana",                   level: "beginner",     description: "Prone backbend strengthening the entire back body",                    cues: "Lie face down, arms by sides. Inhale — lift chest, arms and legs off floor. Exhale — lower down slowly.",                                                               contraindications: [] },
    { name: "Yoga Mudra",                 sanskrit: "Yoga Mudra",                    level: "beginner",     description: "Seated forward fold with hands clasped behind, opens shoulders",       cues: "Sit in Vajrasana, clasp hands behind back. Inhale — open chest. Exhale — fold forward, lift arms away from back.",                                                              contraindications: ["Shoulder/Arm Surgery"] },

    // ── INTERMEDIATE ──
    { name: "Warrior I",                  sanskrit: "Virabhadrasana I",              level: "intermediate", description: "Builds leg strength and opens the chest",                               cues: "Step right foot back, front knee over ankle. Inhale — raise arms overhead. Exhale — sink deeper. Repeat on left side.",                                               contraindications: ["Knee Injury"] },
    { name: "Warrior II",                 sanskrit: "Virabhadrasana II",             level: "intermediate", description: "Strengthens legs and improves focus",                                   cues: "Wide stance, front knee over ankle. Inhale — extend arms wide. Exhale — sink hips lower. Repeat on other side.",                                                   contraindications: ["Knee Injury"] },
    { name: "Reverse Warrior",            sanskrit: "Viparita Virabhadrasana",       level: "intermediate", description: "Side stretch with warrior base, opens the side body",                  cues: "From Warrior II, flip front palm up. Inhale — reach front arm up and back. Exhale — deepen side stretch. Repeat on other side.",                                         contraindications: ["Knee Injury"] },
    { name: "Triangle Pose",              sanskrit: "Utthita Trikonasana",           level: "intermediate", description: "Stretches the sides and strengthens legs",                              cues: "Wide stance, extend front arm down to shin, back arm up. Inhale — open chest. Exhale — extend through both arms. Repeat on other side.",                               contraindications: ["Slipped Disk"] },
    { name: "Extended Side Angle",        sanskrit: "Utthita Parsvakonasana",        level: "intermediate", description: "Full body stretch and stamina builder",                                 cues: "From Warrior II, lower forearm to thigh. Inhale — extend top arm over ear. Exhale — open chest. Repeat on other side.",                                                     contraindications: ["Knee Injury"] },
    { name: "Tree Pose",                  sanskrit: "Vrikshasana",                   level: "intermediate", description: "Balance pose that strengthens the ankles and focus",                    cues: "Stand on right leg, left foot on inner thigh or calf. Inhale — grow tall. Exhale — find fixed gaze. Repeat on left leg.",                                                   contraindications: [] },
    { name: "Standing Forward Bend",      sanskrit: "Uttanasana",                    level: "intermediate", description: "Calms the mind and deeply stretches hamstrings",                       cues: "Feet hip width. Inhale — lengthen spine. Exhale — fold forward from hips, let head hang. Bend knees if needed.",                                                        contraindications: ["Slipped Disk"] },
    { name: "Wide Legged Forward Fold",   sanskrit: "Prasarita Padottanasana",       level: "intermediate", description: "Inner leg and back stretch",                                            cues: "Wide stance. Inhale — lengthen spine. Exhale — fold forward, hands to floor, crown toward floor.",                                                      contraindications: ["Slipped Disk"] },
    { name: "Low Lunge",                  sanskrit: "Anjaneyasana",                  level: "intermediate", description: "Hip flexor stretch and grounding",                                      cues: "Right foot forward, left knee down. Inhale — raise arms overhead. Exhale — sink hips forward. Repeat on left side.",                                                          contraindications: ["Knee Injury"] },
    { name: "High Lunge",                 sanskrit: "Utthita Ashwa Sanchalanasana",  level: "intermediate", description: "Hip flexor stretch and leg strengthener",                               cues: "Right foot forward, left leg straight. Inhale — raise arms overhead. Exhale — sink front knee to 90 degrees. Repeat on left side.",                                                    contraindications: ["Knee Injury"] },
    { name: "Downward Dog",               sanskrit: "Adho Mukha Svanasana",          level: "intermediate", description: "Full body stretch and mild inversion",                                  cues: "Hands and feet on floor, hips high. Inhale — lengthen spine. Exhale — press heels toward floor, straighten legs.",                                                             contraindications: ["High Blood Pressure"] },
    { name: "Plank Pose",                 sanskrit: "Phalakasana",                   level: "intermediate", description: "Core and arm strength foundation",                                      cues: "Hands under shoulders, body straight. Inhale — hold firm. Exhale — engage core and glutes. Do not let hips sag.",                                              contraindications: [] },
    { name: "Half Moon Pose",             sanskrit: "Ardha Chandrasana",             level: "intermediate", description: "Balance and lateral strength",                                          cues: "From Triangle, shift to front foot, lift back leg parallel to floor. Inhale — stack hips. Exhale — extend through lifted heel. Repeat on other side.",                              contraindications: [] },
    { name: "Chair Pose",                 sanskrit: "Utkatasana",                    level: "intermediate", description: "Strengthens thighs, ankles and core",                                  cues: "Feet together, bend knees as if sitting. Inhale — raise arms overhead. Exhale — sink hips lower, chest forward.",                                                    contraindications: ["Knee Injury"] },
    { name: "Camel Pose",                 sanskrit: "Ustrasana",                     level: "intermediate", description: "Heart opening backbend, stretches entire front body",                  cues: "Kneel, hands on lower back. Inhale — open chest to ceiling. Exhale — reach hands back to heels one at a time. Keep hips over knees.",                                         contraindications: ["Slipped Disk", "High Blood Pressure"] },
    { name: "Seated Forward Bend",        sanskrit: "Paschimottanasana",             level: "intermediate", description: "Deep hamstring and back stretch",                                       cues: "Legs extended. Inhale — lengthen spine, raise arms. Exhale — fold forward from hips, reach for feet.",                                                               contraindications: ["Slipped Disk"] },
    { name: "Head to Knee Pose",          sanskrit: "Janu Sirsasana",                level: "intermediate", description: "Hamstring and back stretch with spinal twist",                         cues: "Right leg extended, left foot to inner thigh. Inhale — lengthen spine. Exhale — fold over right leg. Repeat on left side.",                                                             contraindications: ["Slipped Disk"] },
    { name: "Spinal Twist",               sanskrit: "Ardha Matsyendrasana",          level: "intermediate", description: "Seated spinal twist that massages abdominal organs",                   cues: "One leg crossed. Inhale — lengthen spine. Exhale — twist toward bent knee, elbow outside knee. Repeat on other side.",                                                     contraindications: [] },
    { name: "Half Boat",                  sanskrit: "Ardha Navasana",                level: "intermediate", description: "Core strengthening pose, gentler than full boat",                      cues: "Sit, lean back slightly, lift feet to knee height, arms parallel to floor. Inhale — hold. Exhale — engage core strongly.",                                                              contraindications: ["Slipped Disk"] },
    { name: "Boat Pose",                  sanskrit: "Navasana",                      level: "intermediate", description: "Core strengthening pose",                                               cues: "Sit, lean back, lift legs to 45 degrees, arms parallel. Inhale — lengthen spine. Exhale — engage core strongly.",                                                    contraindications: ["Slipped Disk"] },
    { name: "Half Pigeon",                sanskrit: "Ardha Kapotasana",              level: "intermediate", description: "Deep hip opener targeting the piriformis",                             cues: "Right shin forward, left leg back. Inhale — lengthen spine. Exhale — fold forward over front shin. Repeat on left side.",                               contraindications: ["Knee Cartilage Damage", "Knee Injury"] },
    { name: "Butterfly Forward Fold",     sanskrit: "Adho Mukha Baddha Konasana",    level: "intermediate", description: "Deep hip opener with forward fold",                                    cues: "Soles together, knees drop. Inhale — lengthen spine. Exhale — fold forward from hips, forehead toward feet.",                                                                         contraindications: ["Slipped Disk", "Knee Cartilage Damage"] },
    { name: "Gate Pose",                  sanskrit: "Parighasana",                   level: "intermediate", description: "Side body stretch and hip opener",                                      cues: "Kneel, extend right leg to side. Inhale — raise right arm overhead. Exhale — side bend over right leg. Repeat on left side.",                                                       contraindications: ["Knee Injury"] },
    { name: "Garland Pose",               sanskrit: "Malasana",                      level: "intermediate", description: "Deep squat for hip mobility and digestion",                            cues: "Wide stance, squat deep, elbows press knees open. Inhale — lengthen spine. Exhale — sink deeper into squat.",                                                                  contraindications: ["Knee Cartilage Damage"] },
    { name: "Double Leg Raise",           sanskrit: "Dwipadottanasana",              level: "intermediate", description: "Supine both legs raise, strong core strengthener",                     cues: "Lie on back. Inhale — raise both legs to 90 degrees. Exhale — lower slowly without touching floor.",                                                                          contraindications: ["Slipped Disk"] },
    { name: "Equestrian Pose",            sanskrit: "Ashwa Sanchalanasana",          level: "intermediate", description: "Deep hip opener and spinal extension",                                  cues: "Right foot forward between hands, left knee down. Inhale — lift chest, open hip. Exhale — sink deeper. Repeat on left side.",                                               contraindications: ["Knee Injury"] },
    { name: "Half Splits",                sanskrit: "Ardha Hanumanasana",            level: "intermediate", description: "Hamstring and hip flexor stretch",                                      cues: "From low lunge, straighten front leg, flex foot. Inhale — lengthen spine. Exhale — fold over front leg. Repeat on other side.",                                                            contraindications: ["Knee Injury"] },
    { name: "Sage Marichi Pose",          sanskrit: "Marichyasana",                  level: "intermediate", description: "Seated twist with forward fold, stimulates digestion",                 cues: "Right leg extended, left knee bent. Inhale — lengthen spine. Exhale — twist toward left knee, wrap arm. Repeat on other side.",                                                  contraindications: ["Slipped Disk"] },
    { name: "Mill Churning Pose",         sanskrit: "Chakkichalanasana",             level: "intermediate", description: "Seated circular rotation, massages abdominal organs",                  cues: "Legs wide, clasp hands. Inhale — lean forward. Exhale — circle to one side and back. Complete full circles each direction.",                                                 contraindications: ["Slipped Disk"] },
    { name: "Shoulder Stand",             sanskrit: "Sarvangasana",                  level: "intermediate", description: "Inversion that improves circulation and thyroid function",             cues: "Lie on back. Inhale — swing legs overhead. Exhale — support lower back, lift legs vertical. Keep chin tucked.",                                                   contraindications: ["High Blood Pressure", "Cervical Spondylosis", "Heart Condition"] },
    { name: "Plow Pose",                  sanskrit: "Halasana",                      level: "intermediate", description: "Inversion that stretches the spine and shoulders",                     cues: "From shoulder stand, lower legs behind head to floor. Inhale — hold. Exhale — press feet firmly. Keep neck long.",                                                  contraindications: ["High Blood Pressure", "Cervical Spondylosis", "Slipped Disk"] },
    { name: "Fish Pose",                  sanskrit: "Matsyasana",                    level: "intermediate", description: "Chest and throat opener, counterpose to shoulder stand",               cues: "Lie on back, hands under hips. Inhale — arch back, lift chest, crown to floor. Exhale — open throat.",                                                          contraindications: ["Cervical Spondylosis"] },
    { name: "Single Leg Bridge",          sanskrit: "Eka Pada Setu Bandhasana",      level: "intermediate", description: "Bridge with one leg lifted, strengthens glutes and core",              cues: "From bridge, extend right leg up. Inhale — hold hips level. Exhale — press left foot firmly. Repeat on left leg.",                                                               contraindications: ["Knee Injury"] },
    { name: "Wide Angle Seated Forward Fold", sanskrit: "Upavistha Konasana",        level: "intermediate", description: "Inner thigh and hamstring stretch in wide seated position",            cues: "Legs wide. Inhale — lengthen spine. Exhale — fold forward from hips, walk hands forward.",                                                                           contraindications: ["Slipped Disk"] },
    { name: "Revolved Head to Knee",      sanskrit: "Parivrtta Janu Sirsasana",      level: "intermediate", description: "Deep lateral stretch and spinal twist",                                cues: "Right leg extended, left bent. Inhale — lengthen. Exhale — side bend over right leg, reach both arms toward foot. Repeat on left side.",                                                 contraindications: ["Slipped Disk"] },
    { name: "Kneeling Yoga Mudra",        sanskrit: "Balasana Baddha Hasta",         level: "intermediate", description: "Kneeling forward fold with bound hands, opens shoulders",             cues: "Kneel, clasp hands behind back. Inhale — open chest. Exhale — fold forward, lift arms away from back.",                                                                        contraindications: ["Shoulder/Arm Surgery"] },
    { name: "Reclined Thunderbolt",       sanskrit: "Supta Vajrasana",               level: "intermediate", description: "Backbend from kneeling, deep quad and hip flexor stretch",            cues: "From Vajrasana, lean back on hands, then forearms, then floor. Inhale — open chest. Exhale — relax into stretch.",                                                        contraindications: ["Knee Cartilage Damage", "Knee Injury"] },
    { name: "Heron Pose",                 sanskrit: "Kraunchasana",                  level: "intermediate", description: "Seated hamstring and hip flexor stretch",                              cues: "Right leg extended up, hold foot with both hands. Inhale — lengthen spine. Exhale — draw leg closer. Repeat on left side.",                                                       contraindications: ["Knee Injury"] },
    { name: "Cradle the Baby",            sanskrit: "Hindolasana",                   level: "intermediate", description: "Seated hip opener, gently rocks the leg like a cradle",               cues: "Sit tall, cradle right shin in both arms. Inhale — sit tall. Exhale — rock leg side to side. Repeat on left side.",                                                                        contraindications: ["Knee Injury"] },
    { name: "Three Legged Downward Dog",  sanskrit: "Tri Pada Adho Mukha Svanasana", level: "intermediate", description: "Downward dog with hip opening leg lift",                               cues: "From downward dog. Inhale — lift right leg high, hips square. Exhale — press through left heel. Repeat on left leg.",                                                              contraindications: ["High Blood Pressure"] },
    { name: "Goddess Pose",               sanskrit: "Utkata Konasana",               level: "intermediate", description: "Wide squat that strengthens legs and opens hips",                     cues: "Wide stance, toes turned out 45 degrees. Inhale — arms overhead. Exhale — bend knees over toes, lower hips.",                                                                 contraindications: ["Knee Injury"] },
    { name: "Extended Side Gate Pose",    sanskrit: "Utthita Parsva Parighasana",    level: "intermediate", description: "Lateral stretch and hip opener",                                       cues: "Kneel, extend right leg to side. Inhale — both arms up. Exhale — deep side bend over right leg. Repeat on left side.",                                                     contraindications: ["Knee Injury"] },
    { name: "Reverse Plank",              sanskrit: "Purvottanasana",                level: "intermediate", description: "Full front body stretch and arm strengthener",                         cues: "Sit, hands behind hips. Inhale — press hands and feet, lift hips to sky. Exhale — open chest, head drops back gently.",                                                    contraindications: ["Shoulder/Arm Surgery"] },
    { name: "Hand to Foot Pose",          sanskrit: "Padahastasana",                 level: "intermediate", description: "Deep forward fold, stretches entire back body",                       cues: "Stand, fold forward, slide hands under feet. Inhale — lengthen spine. Exhale — fold deeper, elbows bend outward.",                                                            contraindications: ["Slipped Disk"] },
    { name: "Pigeon Pose",                sanskrit: "Eka Pada Rajakapotasana",       level: "intermediate", description: "Deep hip opener and quad stretch",                                     cues: "Right shin forward, left leg extended back. Inhale — lengthen spine. Exhale — fold forward over front shin. Repeat on left side.",                                                   contraindications: ["Knee Cartilage Damage", "Knee Injury"] },

    // ── ADVANCED ──
    { name: "Warrior III",                sanskrit: "Virabhadrasana III",            level: "advanced",     description: "Balance and full body strengthener",                                   cues: "From Warrior I, shift to right foot, hinge forward, lift left leg parallel. Inhale — extend arms forward. Exhale — hold balance. Repeat on left leg.",                        contraindications: ["Knee Injury"] },
    { name: "Eagle Pose",                 sanskrit: "Garudasana",                    level: "advanced",     description: "Balance pose that opens shoulders and hips",                           cues: "Cross right thigh over left, wrap foot if possible. Cross arms, wrap forearms. Inhale — sit deeper. Exhale — lift elbows. Repeat on other side.",                               contraindications: ["Knee Injury"] },
    { name: "Lord of Dance",              sanskrit: "Natarajasana",                  level: "advanced",     description: "Standing balance and backbend, opens chest and shoulders",             cues: "Stand, bend right knee back, hold right foot with right hand. Inhale — kick foot into hand, lift leg. Exhale — hinge forward. Repeat on left side.",                                  contraindications: ["Knee Injury"] },
    { name: "Wheel Pose",                 sanskrit: "Chakrasana",                    level: "advanced",     description: "Full backbend for flexibility and strength",                           cues: "Lie on back, hands beside ears, feet flat. Inhale — press up, straighten arms and legs. Exhale — open chest fully.",                                                          contraindications: ["Slipped Disk", "High Blood Pressure", "Heart Condition"] },
    { name: "Half Wheel",                 sanskrit: "Ardha Chakrasana",              level: "advanced",     description: "Standing backbend, opens chest and shoulders",                         cues: "Stand, hands on lower back. Inhale — open chest to sky. Exhale — arch back, head drops back. Press hips forward.",                                                         contraindications: ["Slipped Disk", "High Blood Pressure"] },
    { name: "Headstand",                  sanskrit: "Sirsasana",                     level: "advanced",     description: "King of asanas, full body inversion",                                  cues: "Forearms on floor, clasp hands, crown between hands. Inhale — walk feet in. Exhale — lift legs slowly overhead. Use wall support initially.",                contraindications: ["High Blood Pressure", "Cervical Spondylosis", "Heart Condition"] },
    { name: "Crow Pose",                  sanskrit: "Bakasana",                      level: "advanced",     description: "Arm balance that builds wrist and core strength",                      cues: "Squat, hands flat, knees on upper arms. Inhale — shift weight forward. Exhale — lift both feet off floor. Engage core.",                                                contraindications: ["Shoulder/Arm Surgery"] },
    { name: "Firefly Pose",               sanskrit: "Tittibhasana",                  level: "advanced",     description: "Advanced arm balance requiring core and hip strength",                 cues: "Squat wide, shoulders under knees. Inhale — shift weight to hands. Exhale — extend legs straight to sides. Engage core strongly.",                                             contraindications: ["Shoulder/Arm Surgery", "Knee Injury"] },
    { name: "Side Plank",                 sanskrit: "Vasisthasana",                  level: "advanced",     description: "Lateral core strengthener and balance pose",                           cues: "From plank, shift to right hand and outer right foot. Inhale — stack hips, raise left arm. Exhale — hold alignment. Repeat on left side.",                                                contraindications: ["Shoulder/Arm Surgery"] },
    { name: "Chaturanga",                 sanskrit: "Chaturanga Dandasana",          level: "advanced",     description: "Low plank that builds upper body and core strength",                   cues: "From plank, inhale to prepare. Exhale — lower halfway, elbows at 90 degrees, hug elbows to sides.",                                                                  contraindications: ["Shoulder/Arm Surgery"] },
    { name: "Revolved Side Angle",        sanskrit: "Parivrtta Parsvakonasana",      level: "advanced",     description: "Twisting lunge that detoxifies and strengthens",                       cues: "From lunge, bring left elbow outside right knee. Inhale — lengthen spine. Exhale — deepen twist, open chest. Repeat on other side.",                                                  contraindications: ["Slipped Disk", "Knee Injury"] },
    { name: "Bow Pose",                   sanskrit: "Dhanurasana",                   level: "advanced",     description: "Full backbend that opens chest and stretches front body",              cues: "Lie prone, bend knees. Inhale — reach back, grab ankles. Exhale — kick feet into hands, lift chest and thighs.",                                                               contraindications: ["Slipped Disk", "High Blood Pressure"] },
    { name: "Cow Face Pose",              sanskrit: "Gomukhasana",                   level: "advanced",     description: "Deep shoulder and hip opener",                                         cues: "Stack right knee over left. Inhale — reach right arm overhead, bend elbow. Exhale — left arm behind back, clasp fingers. Repeat on other side.",                                  contraindications: ["Knee Injury", "Shoulder/Arm Surgery"] },
    { name: "Reclining Hero Pose",        sanskrit: "Supta Virasana",                level: "advanced",     description: "Deep quad and hip flexor stretch in reclined position",                cues: "From Vajrasana, lean back on hands, forearms, then floor. Inhale — open chest. Exhale — let quads release fully.",                                                           contraindications: ["Knee Cartilage Damage", "Knee Injury"] },
    { name: "Sun Salutation",             sanskrit: "Surya Namaskar",                level: "advanced",     description: "Dynamic sequence of 12 poses, full body warmup and energiser",        cues: "Flow through 12 poses with breath: Tadasana — arms up — fold — lunge — plank — Chaturanga — Cobra — Downdog — reverse. Complete both sides.",              contraindications: ["High Blood Pressure", "Heart Condition"] },
  ],

  "Pranayama": [
    { name: "Deep Belly Breathing",  sanskrit: "Diaphragmatic Breathing", level: "beginner",     description: "Calms the nervous system and reduces stress",               cues: "Sit comfortably, hand on belly. Inhale — belly rises. Exhale — belly falls. Keep breath slow and even.",                                    contraindications: [] },
    { name: "Alternate Nostril",     sanskrit: "Nadi Shodhana",           level: "beginner",     description: "Balances left and right brain hemispheres",                 cues: "Close right nostril, inhale left. Close left, exhale right. Inhale right. Close right, exhale left. That is one round.", contraindications: [] },
    { name: "Anulom Vilom",          sanskrit: "Anulom Vilom",            level: "beginner",     description: "Controlled alternate nostril breathing for energy balance", cues: "Inhale left 4 counts. Hold 4 counts. Exhale right 4 counts. Repeat other side.",                                                              contraindications: [] },
    { name: "Bee Breath",            sanskrit: "Bhramari Pranayama",      level: "beginner",     description: "Calms anxiety and reduces stress",                          cues: "Close ears with thumbs, eyes with fingers. Inhale deeply. Exhale — hum like a bee. Feel vibration in skull.",                             contraindications: [] },
    { name: "Box Breathing",         sanskrit: "Sama Vritti",             level: "beginner",     description: "Equal ratio breathing for balance and calm",                cues: "Inhale 4 counts. Hold 4. Exhale 4. Hold 4. That is one round.",                                                                 contraindications: [] },
    { name: "Cooling Breath",        sanskrit: "Sheetali Pranayama",      level: "intermediate", description: "Cools the body and calms the mind",                         cues: "Roll tongue into tube. Inhale through rolled tongue. Close mouth. Exhale through nose. Good for summer practice.",                  contraindications: [] },
    { name: "Victorious Breath",     sanskrit: "Ujjayi Pranayama",        level: "intermediate", description: "Ocean breath for focus and internal heat",                   cues: "Constrict back of throat slightly. Inhale and exhale through nose creating ocean sound. Keep breath long and even.",           contraindications: [] },
    { name: "Skull Shining Breath",  sanskrit: "Kapalabhati",             level: "intermediate", description: "Energising breath for clarity and detox",                   cues: "Sit tall. Sharp forceful exhales through nose, passive inhale. Start 20 pumps, build to 60. Do 3 rounds.",                                    contraindications: ["High Blood Pressure", "Heart Condition", "Epilepsy"] },
    { name: "Bellows Breath",        sanskrit: "Bhastrika Pranayama",     level: "advanced",     description: "Energising and detoxifying breath",                         cues: "Forceful inhale AND exhale through nose, equal intensity. Start slow, build speed. Rest between rounds.",              contraindications: ["High Blood Pressure", "Heart Condition"] },
    { name: "Savasana",              sanskrit: "Savasana",                level: "beginner",     description: "Complete relaxation and integration of practice",           cues: "Lie flat, arms beside body palms up. Close eyes. Release all effort completely.",                                                   contraindications: [] },
    { name: "Yoga Nidra Rest",       sanskrit: "Yoga Nidra",              level: "beginner",     description: "Guided deep relaxation, equivalent to 4 hours sleep",      cues: "Lie in Savasana. Follow guided body scan from toes to crown. Stay aware but completely relaxed.",                                      contraindications: [] },
  ],
};

export function getPosesForPhase(phase, clientInjuries = [], clientConditions = [], clientLevel = "beginner") {
  const allContraindications = [...clientInjuries, ...clientConditions];
  const levelOrder = { beginner: 0, intermediate: 1, advanced: 2 };
  const clientLevelNum = levelOrder[clientLevel] ?? 0;

  return ASANA_LIBRARY[phase]?.filter(pose => {
    const poseLevelNum = levelOrder[pose.level] ?? 0;
    const safeForClient = !pose.contraindications.some(c => allContraindications.includes(c));
    const appropriateLevel = poseLevelNum <= clientLevelNum;
    return safeForClient && appropriateLevel;
  }) || [];
}

export const PHASES = ["Warm-up", "Asanas", "Pranayama"];
